// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwiwtxhscmuiudhktiwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aXd0eGhzY211aXVkaGt0aXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTk4ODUsImV4cCI6MjA1NzY5NTg4NX0._7KC9hBtGESC2-xC8-Q3CG2bIWPWvY3FNo9apVT8jxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);