services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user_automator
      - POSTGRES_PASSWORD=p@ssw0rd@Automator
      - POSTGRES_DB=data_automator
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
